// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.WhiteRabbit")]
[assembly: AssemblyProductAttribute("Plainion.Bees")]
[assembly: AssemblyDescriptionAttribute("Plainion.Bees")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("1.13.0")]
[assembly: AssemblyFileVersionAttribute("1.13.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.WhiteRabbit";
        internal const System.String AssemblyProduct = "Plainion.Bees";
        internal const System.String AssemblyDescription = "Plainion.Bees";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "1.13.0";
        internal const System.String AssemblyFileVersion = "1.13.0";
    }
}
