// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Plainion.WpfBrushes")]
[assembly: AssemblyProduct("Plainion.Bees")]
[assembly: AssemblyDescription("Plainion.Bees")]
[assembly: AssemblyCopyright("Copyright @ 2020")]
[assembly: AssemblyVersion("2.0.0")]
[assembly: AssemblyFileVersion("2.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.WpfBrushes";
        internal const System.String AssemblyProduct = "Plainion.Bees";
        internal const System.String AssemblyDescription = "Plainion.Bees";
        internal const System.String AssemblyCopyright = "Copyright @ 2020";
        internal const System.String AssemblyVersion = "2.0.0";
        internal const System.String AssemblyFileVersion = "2.0.0";
    }
}
